# Generated by Django 2.1.7 on 2019-10-01 03:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('disponivelEstoque', models.BooleanField(default=False, verbose_name='Disponível no estoque')),
                ('quantidadeEstoque', models.IntegerField(verbose_name='Quantidade no estoque')),
                ('afiliadoComissao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comissão do afiliado')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto')),
                ('emPromocao', models.BooleanField(default=False, verbose_name='Em promoção')),
                ('tipo', models.CharField(choices=[(core.models.ProductType('Digital'), 'Digital'), (core.models.ProductType('Físico'), 'Físico')], max_length=5, verbose_name='Tipo')),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tamanho [MB]')),
                ('formato', models.CharField(choices=[(core.models.ProductFileFormat('PDF'), 'PDF'), (core.models.ProductFileFormat('MP4'), 'MP4')], max_length=5, verbose_name='Formato')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dataModificacao', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
                ('produtorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meusProdutos', to='accounts.User', verbose_name='Produtor Principal')),
                ('segundoProdutorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtosAfiliacao', to='accounts.User', verbose_name='Segundo Produtor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProductAffiliated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliatedId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='Id do Afiliado')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Id do Produto')),
            ],
            options={
                'verbose_name': 'Afiliado a um produto',
                'verbose_name_plural': 'Afiliados a um produto',
            },
        ),
    ]
