# Generated by Django 2.1.7 on 2019-04-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliated',
            name='cpf',
            field=models.CharField(default='', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cpf',
            field=models.CharField(default='', max_length=11, verbose_name='CPF'),
        ),
    ]
