# Generated by Django 2.1.7 on 2019-04-06 19:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190406_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliated',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='affiliated',
            name='estado',
            field=models.CharField(choices=[(core.models.BRStates('Acre'), 'Acre'), (core.models.BRStates('Alagoas'), 'Alagoas')], default='', max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cep',
            field=models.CharField(default='', max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='estado',
            field=models.CharField(choices=[(core.models.BRStates('Acre'), 'Acre'), (core.models.BRStates('Alagoas'), 'Alagoas')], default='', max_length=5, verbose_name='Estado'),
        ),
    ]
