# Generated by Django 2.1.7 on 2019-09-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190831_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaffiliated',
            name='affiliatedId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User', verbose_name='Id do Afiliado'),
        ),
        migrations.AlterField(
            model_name='productaffiliated',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Id do Produto'),
        ),
    ]
