# Generated by Django 2.1.7 on 2019-10-01 00:23

import accounts.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(default='', max_length=11, verbose_name='CPF')),
                ('dataNascimento', models.DateField(default='', verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='E-mail')),
                ('emailConfirmado', models.BooleanField(default=False, verbose_name='E-mail confirmado')),
                ('senha', models.CharField(max_length=30, verbose_name='Senha')),
                ('telefone', phone_field.models.PhoneField(default='', help_text='Telefone para contato', max_length=31, verbose_name='Telefone')),
                ('cep', models.CharField(default='', max_length=8, verbose_name='CEP')),
                ('numeroCasa', models.IntegerField(default='', verbose_name='Número')),
                ('rua', models.CharField(default='', max_length=100, verbose_name='Rua')),
                ('bairro', models.CharField(default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[(accounts.models.BRStates('Acre'), 'Acre'), (accounts.models.BRStates('Alagoas'), 'Alagoas'), (accounts.models.BRStates('Amapá'), 'Amapá'), (accounts.models.BRStates('Amazonas'), 'Amazonas'), (accounts.models.BRStates('Bahia'), 'Bahia'), (accounts.models.BRStates('Ceará'), 'Ceará'), (accounts.models.BRStates('Distrito Federal'), 'Distrito Federal'), (accounts.models.BRStates('Espírito Santo'), 'Espírito Santo'), (accounts.models.BRStates('Goiás'), 'Goiás'), (accounts.models.BRStates('Maranhão'), 'Maranhão'), (accounts.models.BRStates('Mato Grosso'), 'Mato Grosso'), (accounts.models.BRStates('Mato Grosso do Sul'), 'Mato Grosso do Sul'), (accounts.models.BRStates('Minas Gerais'), 'Minas Gerais'), (accounts.models.BRStates('Pará'), 'Pará'), (accounts.models.BRStates('Paraíba'), 'Paraíba'), (accounts.models.BRStates('Paraná'), 'Paraná'), (accounts.models.BRStates('Pernambuco'), 'Pernambuco'), (accounts.models.BRStates('Piauí'), 'Piauí'), (accounts.models.BRStates('Rio de Janeiro'), 'Rio de Janeiro'), (accounts.models.BRStates('Rio Grande do Norte'), 'Rio Grande do Norte'), (accounts.models.BRStates('Rio Grande do Sul'), 'Rio Grande do Sul'), (accounts.models.BRStates('Rondônia'), 'Rondônia'), (accounts.models.BRStates('Roraima'), 'Roraima'), (accounts.models.BRStates('Santa Catarina'), 'Santa Catarina'), (accounts.models.BRStates('São Paulo'), 'São Paulo'), (accounts.models.BRStates('Sergipe'), 'Sergipe'), (accounts.models.BRStates('Tocantins'), 'Tocantins')], max_length=5, verbose_name='Estado')),
                ('complemento', models.CharField(default='', max_length=100, verbose_name='Complemento')),
                ('isProdutor', models.BooleanField(default=False, verbose_name='Produtor')),
                ('isAfiliado', models.BooleanField(default=False, verbose_name='Afiliado')),
                ('isAtivo', models.BooleanField(default=True, verbose_name='Afiliado')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dataModificacao', models.DateTimeField(auto_now=True, verbose_name='Última modificação')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
    ]
