# Generated by Django 2.1.7 on 2019-10-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190930_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isAtivo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
